### PR TITLE
Updated visitor tracking

### PR DESCRIPTION
**Pull request by UmarGit**
- [x] Updated visitor tracking

Thank you @enoren5 

Best Regards,
Umar Ahmed

### CODE REVIEW

**Comment by enoren5** [comment]
I branched off, pulled your changes, ran `$ python manage.py makemigrations` and `$ python manage.py migrate`. 

Here is the traceback in a mirrior of my dev server: https://ca06c670eb25.ngrok.io/

I tried backing up my old migrations files and re-ran `$ python manage.py makemigrations` and `$ python manage.py migrate` to create new migrations files. Still, this was the output after entering the above commands:


```
$ python manage.py makemigrations
No changes detected


$ python manage.py migrate         
Operations to perform:
  Apply all migrations: accounts, admin, auth, contenttypes, essays, generators, landings, sessions
Running migrations:
  Applying landings.0001_initial...Traceback (most recent call last):
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: table "landings_aboutcontent" already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/manage.py", line 21, in <module>
    main()
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 232, in handle
    post_migrate_state = executor.migrate(
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
    schema_editor.create_model(model)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 307, in create_model
    self.execute(sql, params or None)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
  File "/home/<user>/dev/projects/python/2018-and-2020/tarot_juicer/venv/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: table "landings_aboutcontent" already exists
```

**Comment by UmarGit** [comment]
Please run below commands
```python
## As we had changed the name of auth toggle, we need to revert all migrations
python manage.py migrate accounts zero

## Double check, if all migrations are created from accounts app
python manage.py makemigrations accounts

## Then safely migrate the app
python manage.py migrate
```

let me know, if any error is raised :smile:

**Comment by enoren5** [comment]
Yes, this works. Thank you @UmarGit!  The session tracking is now removed. 

As for the original issue #64, the language for auth toggle is much clearer. Thanks for the fix! 

However the redirect feature still isn't behaving as intended. For example, even when the protection option is disabled, Django is still serving the gateway template. I tried testing in 3 different web browsers at the same time (as you recommended) and it is still not quite fixed yet.

As for the final requirement, I don't quite completely understand when you say that 'the disappearing links are unnecessary'. You said:

> I think, there is no need to disappear links, when enable protection is not checked, as because we are redirecting user back to home page and user can't access until enable protection is enable again.

Could you please rephrase what you mean and perhaps elaborate?

**Comment by UmarGit** [comment]
@enoren5 

Yes i was talking about ' the disappearing links are unnecessary ', on previous PR because, as I had created the visitor tracking functionality with the help of routing, and giving every user an unique Id, So in that, mechanism, user without an Id, can't access the links.

**Comment by enoren5** [comment]
Now that the sessions visitor feature has been removed, I think it makes sense to implement a conditional to cause  the "Home" menu option along with the "Logout?" link to disappear when the protection is disabled int he Admin Dashboard. Would you agree?

**Comment by UmarGit** [comment]
Hey, brother, I have a suggestion, to completely replace the current, functionality of accounts app ( as you want ), removing the creation of fake users, refactoring the account app, very simple, like as:

> First page is the gateway, whenever the enable protection is unchecked, user can't access, portal ( but with fewer links ) and other urls, but if the enable protection is checked, now user can access, portal and other urls, this can be very simple, currently, I think the previous functionality is not scalable, as we try to add new features, the app, run into some error, I want to make as simple as possible.

that's my suggestion.

**Comment by UmarGit** [comment]
> @UmarGit: Now that the sessions visitor feature has been removed, I think it makes sense to implement a conditional to cause the "Home" menu option along with the "Logout?" link to disappear when the protection is disabled int he Admin Dashboard. Would you agree?

Yes, I had implemented that feature.

**Comment by enoren5** [comment]
> Hey, brother, I have a suggestion, to completely replace the current, functionality of accounts app ( as you want ), removing the creation of fake users, refactoring the account app, very simple, like as:
> 
> > First page is the gateway, whenever the enable protection is unchecked, user can't access, portal ( but with fewer links ) and other urls, but if the enable protection is checked, now user can access, portal and other urls, this can be very simple, currently, I think the previous functionality is not scalable, as we try to add new features, the app, run into some error, I want to make as simple as possible.
> 
> that's my suggestion.

I like how this sounds so far. I'll add a $15 USD as the next milestone on Upwork now.

Would you also be able to clean up all the other deprecated functionality (such as the `random_visitor_password_generator` function inside `/accounts/models.py`?

**Comment by UmarGit** [comment]
> > Hey, brother, I have a suggestion, to completely replace the current, functionality of accounts app ( as you want ), removing the creation of fake users, refactoring the account app, very simple, like as:
> > > First page is the gateway, whenever the enable protection is unchecked, user can't access, portal ( but with fewer links ) and other urls, but if the enable protection is checked, now user can access, portal and other urls, this can be very simple, currently, I think the previous functionality is not scalable, as we try to add new features, the app, run into some error, I want to make as simple as possible.
> > 
> > 
> > that's my suggestion.
> 
> I like how this sounds so far. I'll add a $15 USD as the next milestone on Upwork now.
> 
> Would you also be able to clean up all the other deprecated functionality (such as the `random_visitor_password_generator` function inside `/accounts/models.py`?

Yes, exactly, we can achieve this without any creation of users. Brother, take this build as from my side, you had spent a lot of amount on this app. :smile:

**Comment by enoren5** [comment]
Thank you, my friend! I appreciate your hard work and dedication. I look forward to seeing what you cook up next!

**Comment by UmarGit** [comment]
Sure brother !

**Comment by enoren5** [comment]
I’ve seen your diffs. I am thrilled everything has been simplified. Your code is much easier to follow and understand! Thank you, @UmarGit.

Although I have already identified a few (minor) issues:

1. When I make the migrations and migrate the db, I get this traceback: https://imgur.com/NotZwKg 
2. When navigating to `http://127.0.0.1:8000/article/slashdot` as well as `http://127.0.0.1:8000/article/watchtower`, both show “Page not Found 404. See here: https://imgur.com/BiVg05t 
3. The “Enable protection” option (Auth toggle) still doesn’t work. See here: https://youtu.be/3F7gshEihfs 
As you can see in that video, whether the “Enable protection” option is checked or unchecked, there is always a gateway. The intended behavior is that, when Enable protection is unchecked, Django should skip the gateway template and instead serve the portal template.
4. When the site is not protected by the gateway:
    * The ”Logout?” link on the `http://127.0.0.1:8000/portal` template should disappear
    * “Home” on the partials/_navbar.html element should also disappear

Both 3.  + 4. were part of the original proposal on Upwork and remain unresolved. Would you be able to complete these two requirements?

I know you’ve said that 4. isn’t necessary or practical. But I believe it is necessary and now that you have refactored and simplified the accounts app code, is 4. easier to implement and more practical?

**Comment by UmarGit** [comment]
> I’ve seen your diffs. I am thrilled everything has been simplified. Your code is much easier to follow and understand! Thank you, @UmarGit.
> 
> Although I have already identified a few (minor) issues:
> 
> 1. When I make the migrations and migrate the db, I get this traceback: https://imgur.com/NotZwKg
> 2. When navigating to `http://127.0.0.1:8000/article/slashdot` as well as `http://127.0.0.1:8000/article/watchtower`, both show “Page not Found 404. See here: https://imgur.com/BiVg05t
> 3. The “Enable protection” option (Auth toggle) still doesn’t work. See here: https://youtu.be/3F7gshEihfs
>    As you can see in that video, whether the “Enable protection” option is checked or unchecked, there is always a gateway. The intended behavior is that, when Enable protection is unchecked, Django should skip the gateway template and instead serve the portal template.
> 4. When the site is not protected by the gateway:
>    
>    * The ”Logout?” link on the `http://127.0.0.1:8000/portal` template should disappear
>    * “Home” on the partials/_navbar.html element should also disappear
> 
> Both 3. + 4. were part of the original proposal on Upwork and remain unresolved. Would you be able to complete these two requirements?
> 
> I know you’ve said that 4. isn’t necessary or practical. But I believe it is necessary and now that you have refactored and simplified the accounts app code, is 4. easier to implement and more practical?

Okay @enoren5 brother,I will make it as intended and I also make video of how the app works. 😃

**Comment by enoren5** [comment]
Issue #64 resolved. Thanks again, @UmarGit!

**Comment by UmarGit** [comment]
> Issue #64 resolved. Thanks again, @UmarGit!

Yay !!

**Pull request merged**
