### PR TITLE
Re arrange tarot key attribute

### PR DESCRIPTION
**Pull request by abubakarA-Dot**

### CODE REVIEW

**Comment by enoren5** [comment]
Hi @abubakarA-Dot : Thanks for the PR! I resolved the merge conflict and kept your static path instead of using Jinja syntax to refer to the icon link.

I tested your CSS. The desired effect looks good but only when the browser window is between 700px and 768px wide. You used this media query: `@media (min-width: 700px) and (max-width: 768px) `. However the requirement is for resolutions greater than 700px. So for example on a 1080p monitor, the CSS rule should apply with a width of 1920px. So the desired appearance with the attributes showing to the right side of the card card (as depicted  in the mockup screenshot in Issue #193) should really show at any resolution greater than 700px.

When replacing:
```
@media (min-width: 700px) and (max-width: 768px) 
```
with:
```
@media (min-width: 700px) {
 section.general {...}
} 
```
... the tarot card should appear in the centre off set slightly to the left and the attribute list should appear in the centre but  offset slightly to the right at all resolutions greater than 700px.

To illustrate better, when I make that change, this is how the page elements render at a 1920px resolution:

This is 1920px width -Screenshot_2022-08-29_10-42-49

Above the tarot card image is all the way over to the left.  Below  is more specifically how 1920px windows should render. As you can see, to the right of the centre green seem, the attributes are listed. And then to the left of the centre green seem, the tarot card image appears slightly to the left. This is how the card and attributes should appear at all resolutions greater than 700px. By the way, the `text-align` property should have a `left` value instead of `center` value. That would be perfect. I have tried making this change locally but I can't push it to your remote repo. Anyways, here is a more accurate mockup describing the desired behavior:

This is how 1920px width should look -Screenshot_2022-08-29_10-42-49

**Comment by abubakarA-Dot** [comment]
Understood. perfectly described. thanks

**Comment by enoren5** [comment]
Hi Abu!

The tarot card is now positioned correctly. Thank you. Now we need to position the 5 attributes to the right in the same way. Currently, when you adjust the window width, they seem lost, moving back and forth (see below). That is not we we are aiming for here. Instead the 5 attributes need to idle at the center of the screen to the right of the green marker (line) in the image in my previous comment. There is a verticle line at the centre of the page. At resolutions greater than 700px, the tarot card needs to be positioned to the left and the attributes need to be positioned to the right. They can't be moving around with large gaps in between.

Here is a demo of the problematic beaviour:

https://user-images.githubusercontent.com/6686723/187815468-5eb5de3f-8cae-4535-a089-40b4a0799af3.mp4

**Comment by enoren5** [comment]
Hi Abu. Thanks for the updates. I tested your changes. I don't see a difference. It is still very problematic. For example, at larger resolutions, there is still a huge gap and lots of undeseriable empty space as you can see with the green mark here:

For Abu - empty space

When you adjust the width of the window, the ".esoteric-attributes" class element contents dance and move back and forth. I am trying to avoid this. 

Instead, the ".esoteric-attributes" class element contents need to remain static at all resolutions greater than 700px positioned  as it appears below way with no empty space between the card and attributes list. When the web visitor expands the window size, the attributes shouldn't move back and forth:

For Abu - no empty space - all resolutions greater than 700px

**Pull request merged**
