### PR TITLE
Abubakar

### PR DESCRIPTION
**Pull request by abubakarA-Dot**
I just resolved issue #166 making all the apps' URLs protected dynamically. now, no one can breach your web's security by just adding a URL(of your apps that were not included in the protected URLs list)
@enoren5  please review the new changes and let me know.

### CODE REVIEW

**Comment by enoren5** [comment]
Check out this video:

https://user-images.githubusercontent.com/6686723/146635688-02ddab53-fb1b-40b3-b608-c521d51dbdcf.mp4

To explain what is going on in that video, in the beginning, in the shell on the left, I run: `$ git status` which demonstrates that the code running is on the `abubakarA-Dot-abubakar` branch (PR #173) with the latest changes in `middlewares.py`. 

Right after that, I invoke the Django runserver command. 

Next, I exit from the existing web webpage out to the gateway template. I proceed to enter a valid passphrase. That grants me access and I am able to descend down into the website. As you can see in the shell, in blue font, it says: “New session of 1 minutes has started”. This is running as intended and expected so far.

Now it is time to wait 1 minute. 

The session eventually does expire at the one minute mark. When I click on the `about` page, Django then kicks the web visitor (me) back out to the gateway. You can see in the Django shell in red font `Session timeout at: /about`. So this works fine up to this point.  _HOWEVER_, without re-entering the required passphrase, when I manually enter a URL (I tried: `http://127.0.0.1:8000/tarot_key/12`), the gateway page was completely bypassed and Django served content which should have been protected.

Therefore, even with the latest patch and url patterns imported and declared at lines 37-39 in middlewares.py, the session timeout vulnerability is still present. This needs to be corrected.

**Comment by enoren5** [comment]
Hi Abu, I tested your PR. Right now it behaves as intended. #166 has been resolved but I feel like you kind of 'cheated' in a way by writing a new middleware script. There is nothing wrong with re-writing a script to make it better. I am glad you did it. Thank you for completing the trask. But I am a bit shocked why you would call it `another.py`. That has me baffled and perplexed. In order to complete this requirement and move on to the next Issue, could you first please refactor `another.py` so that there is just one middle ware script named `middlewares.py`? Once this has been fixed I will merge your PR #173 into `master`.

**Comment by enoren5** [comment]
Can the original `middlewares.py` can be completely discarded? If so, then some file name refactoring should be fairly straightforward. 

Or does the new middleware script you wrote require your new one and old? Like, does the app require both original and new at the same time?

**Comment by enoren5** [comment]
When `is_protected` option toggle is toggled off for the `accounts` app, Django should stop serving `gateway.html` and serve `portal.html` instead. This is how the previous middleware behaved. But since @abubakarA-Dot  rewrote it from scratch, we lost this feature. Right now even if `is_protected` is switched off, it is still protected. This functionality needs to be restored to its original state.

When Admin access is detected, Django should circumvent the gateway/middle ware protection and a banner should appear at the top of every web page which says: "Admin Only Access". This feature was originally described in Issue #122 and implemetned in PR #131.

**Comment by abubakarA-Dot** [comment]
> Hi @abubakarA-Dot, I tested your PR. Right now it behaves as intended. #166 has been resolved but I feel like you kind of 'cheated' in a way by writing a new middleware script. There is nothing wrong with re-writing a script to make it better. I am glad you did it. Thank you for completing the trask. But I am a bit shocked why you would call it `another.py`. That has me baffled and perplexed. In order to complete this requirement and move on to the next Issue, could you first please refactor `another.py` so that there is just one middle ware script named `middlewares.py`? Once this has been fixed I will merge your PR #173 into `master`.

hi. Well I will rename it to a meaningful file and let me explain why I worked in a separate file was because I tried many ways to fix it in a single file but I couldn't so when I tried my solution in a new file then it resolved. and I will rename it with a meaningful filename so that in future you can easily recognize the files and do whatever according to your needs. thanks

**Comment by abubakarA-Dot** [comment]
> Can the original `middlewares.py` can be completely discarded? If so, then some file name refactoring should be fairly straightforward.
> 
> Or does the new middleware script you wrote require your new one and old? Like, does the app require both original and new at the same time?

no, all of the middle wares required. so nothing can be discarded. yes, we require both original and new files at the same time

**Comment by abubakarA-Dot** [comment]
> I just discovered something new. When `is_protected` option toggle is toggled off for the `accounts` app, Django should stop serving `gateway.html` and serve `portal.html` instead. This is how the previous middleware behaved. But since @abubakarA-Dot rewrote it from scratch, we lost this feature. Right now even if `is_protected` is switched off, it is still protected. This functionality needs to be restored to its original state.
> 
> When Admin access is detected, Django should circumvent the gateway/middle ware protection and a banner should appear at the top of every web page which says: "Admin Only Access". This feature was originally described in Issue #122 and implemetned in PR #131.

thanks for letting me know. I got your point of view and I will fix it as t was before. thanks again.

**Comment by enoren5** [comment]
Hi @abubakarA-Dot: Thanks for making the changes however I can't see them yet. Did you forget to push your changes to your remote branch? I would  need you to push your changes so that I can pull them and begin testing.

**Comment by enoren5** [comment]
I tested your changes, @abubakarA-Dot. `is_protected` now behaves like it did before. Thank you for fixing this. You're doing a good job so far.

Now let's discuss the "Admin Only Access" feature that needs to be restored.

When `is_protected` and `Nuclear` option is switched on (for the `accounts` app) and a Django Admin is logged into the Dashboard, this user should be able to navigate around the website (for example see the `about` page or `essay_list` or other pages) even though all other public web traffic should be locked out at the `gateway` page. When this Admin is logged in and navigating around, a horizontal 256px tall white banner with large black font that says: "Admin Only Access" should pinned to the top of every web page. This should work for all templates. The purpose of this feature is to inform me (the Admin) that only I am logged in and I can trust that public visitors are resitrcited and locked out. 

This feature was already implemented but is no longer present since you started this PR. So you would need to restore this functionality as well. Once this is restored, we should be able to move on to the next Issue.

**Comment by abubakarA-Dot** [comment]
> 

thanks.
Yes, I know that the "Admin Only Access" feature was there and it is not working right now and it is already implemented and I will restore it now. and thanks for your compliment.

**Comment by abubakarA-Dot** [comment]
> I tested your changes, @abubakarA-Dot. `is_protected` now behaves like it did before. Thank you for fixing this. You're doing a good job so far.
> 
> Now let's discuss the "Admin Only Access" feature that needs to be restored.
> 
> When `is_protected` and `Nuclear` option is switched on (for the `accounts` app) and a Django Admin is logged into the Dashboard, this user should be able to navigate around the website (for example see the `about` page or `essay_list` or other pages) even though all other public web traffic should be locked out at the `gateway` page. When this Admin is logged in and navigating around, a horizontal 256px tall white banner with large black font that says: "Admin Only Access" should pinned to the top of every web page. This should work for all templates. The purpose of this feature is to inform me (the Admin) that only I am logged in and I can trust that public visitors are resitrcited and locked out.
> 
> This feature was already implemented but is no longer present since you started this PR. So you would need to restore this functionality as well. Once this is restored, we should be able to move on to the next Issue.

@enoren5  I just fixed back Admin only access feature. I want to explain how will it work. you just need to switch on the nuclear option to restrict any other user from using your website except "ADMIN". so it is not necessary to switch on the is_protected option for admin use.

**Comment by enoren5** [comment]
Hi @abubakarA-Dot! Thanks for fixing this. Almost there. Before I finally merge these changes into master and mark this Issue as resolved, when Django serves the `gateway.html` template, the red banner saying "Warning: Admin Only Access"  must be removed. The  "Admin Only Access" banner (the white one) should only appear to the  Django Admin user when they descend down into the `portal` (and all the other subsequent web pages).

**Comment by abubakarA-Dot** [comment]
@enoren5 thanks for telling me. yes, I thought for a while that the Portal page should appear instead of a gateway. I will resolve it now.

**Pull request closed without merging**
