### PR TITLE
Created a mechanism for dynamic user handling

### PR DESCRIPTION
**Pull request by UmarGit**
- [x] #60  Created a mechanism for dynamic user handling

> Instead of creating a fake user from setting.py ( which is hardcoded ) and we need a dynamic mechanism to create users with a random name and password. So, I created some methods that create a random user, If it does not exist in the current session of the browser. 

> Changed the URL pattern for accessing the portal. 

> Updated views.py to check for the user in the current session and also updated the Auth toggle functionality to kick all users at once.

> Lastly updated middleware redirections.

That's all, I had done, thank you @enoren5  

Best Regards,
Umar Ahmed

### CODE REVIEW

**Comment by enoren5** [comment]
Hi @UmarGit! Thanks for the PR. I tested it. It generally works, like when traversing back and forth between `gateway.html` and `portal.html`. But when clicking on the "Tarot at Random" or "@FILM" links (on the `portal.html` page), I encounter this traceback: https://imgur.com/a/8LT3VBY

**Comment by UmarGit** [comment]
Okay @enoren5 , let me check brother.

**Comment by UmarGit** [comment]
The issue is because I have made some changes to the routings, that's why Django didn't find that URL, now I have updated the generators, about ( page URLs ).

I have also changed some URL routing, then also double-check to migrate the apps as follows:
`python manage.py migrate landings`
`python manage.py migrate essays`
`python manage.py migrate generators`
then `python manage.py makemigrations`

And that's all I had done

**Comment by enoren5** [comment]
Hi @UmarGit: Now `tarot keys` and the `about` pages render properly. Thank you for fixing that! But there other locations which are still throwing 'NoReverseMatch' such as: `http://127.0.0.1:8000/essay_list` and `http://127.0.0.1:8000/article/slashdot/`. Take a look here (along with the commands and their output in my terminal): https://imgur.com/nrxoJTJ

**Comment by UmarGit** [comment]
Okay @enoren5 , I am checking that

**Comment by UmarGit** [comment]
**_Fixed sessions_** 

And that's all I had done

**Comment by enoren5** [comment]
Thanks, @UmarGit! I sent you a message on Upwork about a potential next milestone. Check it when you can! :)

**Comment by enoren5** [comment]
Issue #60 resolved!

**Pull request merged**
