### PR TITLE
Rewrite accounts app

### PR DESCRIPTION
**Pull request by UmarGit**
- [x] #56 Rewrite `accounts` app from scratch as:

> Added a dot env package to secure the secret keys in a safe place.

> Updated `middelwares.py` by adding code to initially create a field in auth toggle as `active = False`, So initially URLs will not be transferred to `/portal`, wait here what about other URLs? we can restrict them well later.

> Updated `models.py` by adding code to initially create a user ( if not present or created yet ) based on the given credentials.
added a new model called passphrase to store and change different passphrases.

> Registered the passphrase model in `admin.py`

> Updated `urls.py` by adding two more URLs entry as `portal and logout`.

> Updated `views.py` by adding code for the index function and added the functionality to automatically check for all passphrases values in the DB and check if the entered passphrase is validated or not? ( if satisfied then, as well as toggling the active model in Auth Toggle to True ). For the portal URL, a Django decorator called `@login_required` will be preventing users to keep away without logging in to the system using the correct passphrase. A logout function, added to again toggling the active model in Auth Toggle to False and deleting the created user.

That's all, I had done, thank you @enoren5 

Best Regards,
Umar Ahmed

### CODE REVIEW

**Comment by enoren5** [comment]
Hi @UmarGit! 

I tested your changes. Everything runs very well so far. Great work! 

To answer your first question, all the other urls should be protected, not just portal. So if a web visitor navigates to an essay or tarot_key, then Django should serve them the gateway until they enter a correct passphrase.

You asked a second question which I don't completely understand. You said:
> Updated views.py by adding code for the index function and added the functionality to automatically check for all passphrases values in the DB and check if the entered passphrase is validated or not? ( if satisfied then, as well as toggling the active model in Auth Toggle to True )

Could you please clarify what you mean?

Here are some of my remaining questions:
1. For the `accounts` app, in the AdminDashboard, can you show a list of passphrases submitted by the admin user? Also: the admin user should be able to delete one of the passphrases listed.
2. Could you also add a timer so that after 1 hour goes by, Django will re-route them to `gateway.html` requiring the web visitor to re-enter a valid passphrase?

**Comment by UmarGit** [comment]
Hey @enoren5 

> I didn't ask any question above, I was trying to explain the workflow to you only.

To answer your questions:

> 1. You can visit [admin view on](http://127.0.0.1:8000/admin) to add passphrases, delete or modify them.

> 2. Okay I will it like a session time out thing and explain it to you after implementing.

thank you @enoren5

Best Regards,
Umar Ahmed

**Comment by enoren5** [comment]
Thanks Umar! Issue #58 has been resolved. I am curious to learn more about your thoughts on the session time-out feature that you said you could explain.

**Comment by UmarGit** [comment]
Yes @enoren5 sure !

**Pull request merged**
