### PR TITLE
Update static files

### PR DESCRIPTION
**Pull request by UmarGit**
## Static Files Issue

> I have read the official Django's documentation, So, I removed `staticfiles` folder, So by running `python manage.py collectstatic --noinput --clear --no-post-process
`, we can revive the folder and files on production. Just we must not add static files folder to `.gitignore` to be read by Heroku in production. 

that's all I had done, @enoren5 brother ❤️

### CODE REVIEW

**Comment by enoren5** [comment]
Hi, @UmarGit! Thank you for making this change. But there seems to be a regression. 

I fetched your changes into a testing branch locally and tested. After invoking, `$ python manage.py collectstatic --no-input`,  static files are now appearing to retain the problem (originally outlined in Issue #91) with [hashes being appended causing Django to serve missing images and CSS files](https://i.imgur.com/2hixRzj.jpg). Your solution to that problem was to track `/staticfiles` which kind of worked but it's against Django best practices because only one static file directory must be tracked but for some reason you made it so that Django needs to track both. 

For the purposes of my project, going forward, the only tracked static folder must be: `/tarot_juicer/tarot_juicer/static/`. 

Therefore, the two problems that must still be resolved are:
1. `/staticfiles` must no longer be tracked
2. The file name hashing needs to stop

Umar, you said:

> Just we must not add static files folder to .gitignore to be read by Heroku in production.

According to `.gitignore`, these are the first 5 lines:
```
# migrations
/static
/media
# staticfiles
# /staticfiles
```
Since `/staticfiles` directory must no longer be tracked, if I understand correctly, then lines 4 and 5 should be uncommented. Is this correct? If I have misunderstood, then please clarify further.

Thanks, Umar

**Comment by UmarGit** [comment]
> Hi, @UmarGit! Thank you for making this change. But there seems to be a regression. 
> 
> I fetched your changes into a testing branch locally and tested. After invoking, `$ python manage.py collectstatic --no-input`,  static files are now appearing to retain the problem (originally outlined in Issue #91) with [hashes being appended causing Django to serve missing images and CSS files](https://i.imgur.com/2hixRzj.jpg). Your solution to that problem was to track `/staticfiles` which kind of worked but it's against Django best practices because only one static file directory must be tracked but for some reason you made it so that Django needs to track both. 
> 
> For the purposes of my project, going forward, the only tracked static folder must be: `/tarot_juicer/tarot_juicer/static/`. 
> 
> Therefore, the two problems that must still be resolved are:
> 1. `/staticfiles` must no longer be tracked
> 2. The file name hashing needs to stop
> 
> Umar, you said:
> 
> > Just we must not add static files folder to .gitignore to be read by Heroku in production.
> 
> According to `.gitignore`, these are the first 5 lines:
> ```
> # migrations
> /static
> /media
> # staticfiles
> # /staticfiles
> ```
> Since `/staticfiles` directory must no longer be tracked, if I understand correctly, then lines 4 and 5 should be uncommented. Is this correct? If I have misunderstood, then please clarify further.
> 
> Thanks, Umar 
> 

100% agreed brother, I got your point

**Comment by UmarGit** [comment]
@enoren5 brother

Sorry for a little mistake in the collectstatic command above it should run like:
```
python manage.py collectstatic --noinput --clear --no-post-process
``` 
I forgot it, I also state this `hashed file` issue on this [comment](https://github.com/enoren5/tarot_juicer/issues/92#issuecomment-810353548)

By running the above command will not copy the hashed files.


> Next, the concept is like, the `tarot_juicer/tarot_juicer/static` folder **used to serve files only when on development mode** only and when we run the above collect static command a new folder appears called `tarot_juicer/staticfiles` **which is only used for production on Heroku**.

> So if you run collect static command for testing on local environment, you will notice git will start to track the files init, but we should delete the `tarot_juicer/staticfiles` folder after testing, **we must not add `tarot_juicer/staticfiles` folder to `.gitignore` ( currently `.gitignore` is okay ✌️ )**, As it is only for production purposes only.

Thank you @enoren5 brother 🥳🧐🙌❤️👌😍😘

**Comment by enoren5** [comment]
I am still misunderstanding something here, @UmarGit. Pardon my newbie question and for my confusion.

Locally in my dev environment, I deleted `tarot_juicer/staticfiles/` and Django is still serving static files with hashes. See here: https://i.imgur.com/ssDh54f.jpg

When I run, `$ python manage.py collectstatic --noinput --clear --no-post-process`, then `tarot_juicer/staticfiles` is generated containing imgs, css, javascript. There are no hashes in their file names. But Django continues to serve static files with hashes when I navigate to the tarot_key template, for example this address here: `http://localhost:8000/tarot_key/16#`. When you reveal the card album, thumbnails for "The Fool" (K0.jpg) and "The World" (K21.jpg) still have hashes.  

The .jpg on imgur captures the same behaviour before (and after) I run your special collectstatic command locally.

**Comment by UmarGit** [comment]
@enoren5 brother, checking now

**Comment by enoren5** [comment]
The contents of all the static directories don't have hashes, but my Django dev server is still serving images with hashes and I have no idea why.

**Comment by UmarGit** [comment]
Brother which database are you using currently, sqlite ?

So I can check with it on my side 🤗

**Comment by enoren5** [comment]
There are a total of 263 items inside `staticfiles` at 11.1MB. Here is the db.sqlite3 binary that I am using: https://www.dropbox.com/s/vl0ogrdrq58o4e1/db.sqlite3?dl=0

**Pull request merged**
