### PR TITLE
Update broken static files

### PR DESCRIPTION
**Pull request by UmarGit**
[x] #74 Update broken static files

> There is some CSS references to files, that didn't exits now, that's why the `collectstatic` command is throwing error, I had removed the obsolete path of files, that didn't exist. Now after merging this branch, we can safely run  `collectstatic` command as:

```python
python manage.py collectstatic
```
That's all I had done,
Best Regards
Umar Ahmed

### CODE REVIEW

**Comment by enoren5** [comment]
Thanks, @UmarGit! I merged the changes into my master branch, pushed to Heroku and ran collectstatic. The card images when selecting "Show/Hide Album" are still empty. See [here](https://i.imgur.com/xlnAU9H.jpg) on imgur.

**Comment by enoren5** [comment]
Also, the 404 [is still a problem](https://i.imgur.com/G5TVRn7.jpg). To reproduce the problem, try adding a forward slash (`/`) to the first path parameter for  watchtower and slashdot in `/essays/urls.py`. Then save the change. Try navigating to `http://127.0.0.1:8000/article/slashdot/`. The 404 is present. But then when I go to remove the (`/`) from the first path pamarter, save the file, and try navigating back to `http://127.0.0.1:8000/article/slashdot/` and the 404 remains.

**Comment by UmarGit** [comment]
Okay brother, I will revise the changes, in the morning.

**Comment by UmarGit** [comment]
Hey @enoren5,

> The problem in the card images is when we check the source of image in console than it is picking up the img as 

```python
/static//img/thumbnails/K04.jpg #which is wrong it must be

/static/img/thumbnails/K04.jpg #correct
```

So when I checked the `tarot_key.html` then I kept to know that image is returned using:

```python
{{ STATIC_URL }}{{ card.tarot_card_thumbnail.url }} 
```
In which STATIC_URL returns `/static/` and `card.tarot_card_thumbnail.url` 
is returning `/img/thumbnails/K04.jpg` which is `/static//img/thumbnails/K04.jpg`

So I see the above parameters to get correct static url,

Then, I see you had used `static` to get url as '/static'

So, By then I used:
```python
{% static card.tarot_card_thumbnail.url %}
```
which returns
```python
/static/img/thumbnails/K04.jpg #which is correct
```

Hope You will get my point 

# :relaxed:

**Comment by UmarGit** [comment]
> Also, the 404 [is still a problem](https://i.imgur.com/G5TVRn7.jpg). To reproduce the problem, try adding a forward slash (`/`) to the first path parameter for watchtower and slashdot in `/essays/urls.py`. Then save the change. Try navigating to `http://127.0.0.1:8000/article/slashdot/`. The 404 is present. But then when I go to remove the (`/`) from the first path pamarter, save the file, and try navigating back to `http://127.0.0.1:8000/article/slashdot` and the 404 remains.

Hey @enoren5, 

### The 404s are resolved as you can see [404](https://tarot-juicer-next-iter.herokuapp.com/article/slashdot)

The error is basically is in essays's url.py

In that as you can see:

```python
path('article/<str:web_address>/', views.article, name='article')
```

Now for every path starts with article and include a web-address then it will take it to the article views,

Before my I had implement the changes, the slashdot or watchtower can be accessed through.

```python
path('article/slashdot/', views.slashdot, name='slashdot')
```

In which, it not going to the slashdot's view instead dijango reads the url as the article/web_address, So that's why it doesnt found an article in article view with the web slug as `slashdot`.

So to resolve this dijango behaviour, and to distinguish each url, I had removed the / sign from slashdot and watchtower's url, So that they can be accessed separatly, Instead of merging with the article's function.

```python
path('article/<str:web_address>/', views.article, name='article') # article/someaddress/

path('article/slashdot', views.slashdot, name='slashdot') #article/slashdot

path('article/watchtower', views.watchtower, name='watchtower') #article/watchtower

#Now they are separated from each other
```

**Comment by enoren5** [comment]
Thanks, @UmarGit!

Based on your feedback and analysis, I resolved to changing line 25 in the `tarot_key.html` template from this:

> {{ STATIC_URL }}{{ card.tarot_card_thumbnail.url }}

to this:

> {% static card.tarot_card_thumbnail.url %}

That resolved the issue! Now the thumbnails are parsing as intended.

In `essays/urls.py`, I commented out:

> path('article/<str:web_address>/', views.article, name='article'),

...and then re-added the forward slashes `/` to lines 10 and 11. No more 404! Thanks again, Umar!

**Pull request closed without merging**
